name: media_picker_widget
description: A widget that picks media files from storage and allows you to place anywhere in the widget tree.
version: 1.0.8
homepage: https://github.com/rafidgotit/media_picker_widget

environment:
  sdk: ">=3.6.0 <=4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: ^3.6.4
  sliding_up_panel: ^2.0.0+1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: